package com.bluetoothmicrecord;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bluetoothmicrecord.bean.BluetoothDevices;
import com.bluetoothmicrecord.bean.RecordAudioFile;

import com.bluetoothmicrecord.BluetoothDevicesDao;
import com.bluetoothmicrecord.RecordAudioFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bluetoothDevicesDaoConfig;
    private final DaoConfig recordAudioFileDaoConfig;

    private final BluetoothDevicesDao bluetoothDevicesDao;
    private final RecordAudioFileDao recordAudioFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bluetoothDevicesDaoConfig = daoConfigMap.get(BluetoothDevicesDao.class).clone();
        bluetoothDevicesDaoConfig.initIdentityScope(type);

        recordAudioFileDaoConfig = daoConfigMap.get(RecordAudioFileDao.class).clone();
        recordAudioFileDaoConfig.initIdentityScope(type);

        bluetoothDevicesDao = new BluetoothDevicesDao(bluetoothDevicesDaoConfig, this);
        recordAudioFileDao = new RecordAudioFileDao(recordAudioFileDaoConfig, this);

        registerDao(BluetoothDevices.class, bluetoothDevicesDao);
        registerDao(RecordAudioFile.class, recordAudioFileDao);
    }
    
    public void clear() {
        bluetoothDevicesDaoConfig.clearIdentityScope();
        recordAudioFileDaoConfig.clearIdentityScope();
    }

    public BluetoothDevicesDao getBluetoothDevicesDao() {
        return bluetoothDevicesDao;
    }

    public RecordAudioFileDao getRecordAudioFileDao() {
        return recordAudioFileDao;
    }

}
